### PR TITLE
Update to .NET 7: Support for EFCore 3.0 and higher

### PR DESCRIPTION
**Pull request by atharkes**
Updated targeting framework and dependencies as the current implementation doesn't work anymore with any EFCore version above 3.0

Removed the framework version as I didn't want to bother with it.

### CODE REVIEW

**Comment by atharkes** [comment]
Link to #14

**Comment by StefH** [comment]
@atharkes 
Thank you for this PR.

However, all projects + files seem to changed and older framework support has been removed.

I can understand your support and need for .NET 7 + EFCore 7 for this library, so I want to ask you if you can create a new PR in which you create a new project named `QueryInterceptor.EntityFrameworkCore7` which includes support for QueryInterceptor.EntityFrameworkCore version 7.

And keep all other projects + files the same.

**Comment by atharkes** [comment]
Currently it has no priority to me, as I have little experience with multiple version support. Hence, sorry for butchering your code ;)

Mostly made this PR as reference for others: It all works fine after upgrading the packages and changing some method signatures.

**Comment by atharkes** [comment]
I added a 'minimal' branch to my repository to show more 'minimal' changes, but I can't really test it as the c# versions are so out of date.

**Comment by StefH** [comment]
Closing in favor of https://github.com/StefH/QueryInterceptor.Core/pull/15

**Pull request closed without merging**
